[default.probe]
# The communication protocol used between the debug probe and the microcontroller
protocol = "Swd"

# OPTIONAL — Only needed if you have multiple probes connected at the same time:
# usb_vid = "1366"           # J-Link Vendor ID
# usb_pid = "1051"           # J-Link Product ID
# serial = "001050230903"    # Unique serial number for probe selection

[default.flashing]
enabled = true                        # Automatically flash the MCU when running
restore_unwritten_bytes = false      # Default — only modified flash pages are changed
do_chip_erase = false                # Set to true if you want a full chip erase before flashing

[default.reset]
enabled = true                       # Reset the MCU after flashing
halt_afterwards = false              # MCU starts running immediately after reset

[default.general]
chip = "nRF52833_xxAA"               # The exact microcontroller model you're working with
log_level = "WARN"                   # Controls verbosity of cargo-embed output
connect_under_reset = false          # Normally false; set to true only if MCU is unresponsive

[default.rtt]
enabled = true                       # Enable RTT logging (Real-Time Transfer over SWD)
timeout = 3000                       # Wait up to 3000 ms to detect RTT
show_timestamps = true               # Display timestamps in the RTT output
log_enabled = false                  # Don't save logs to file by default
log_path = "./logs"                  # Path to store logs if log_enabled = true

# OPTIONAL — Choose how to handle log buffer overflow:
# - NoBlockSkip: Fastest, skips data if buffer is full
# - NoBlockTrim: Writes as much as fits, discards the rest
# - BlockIfFull: Waits until host reads data, can freeze your app
# up_mode = "BlockIfFull"

# OPTIONAL — Define RTT channels if you use more than one, or defmt logging
# channels = [
#     { up = 0, format = "String" }
# ]

[default.gdb]
enabled = false  # Disable GDB server; not needed when using cargo-embed/probe-rs